import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // Auto-generated sidebars from docs
  installationAndSetupSidebar: [{ type: 'autogenerated', dirName: 'installation-and-setup' }],
  faqsSidebar: [
    {
      type: 'category',
      label: 'FAQs',
      link: { type: 'doc', id: 'faqs/index' },
      collapsed: false,
      items: [
        'faqs/faq-gameplay',
        'faqs/faq-technical',
      ],
    },
  ],
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'guides/index' },
      collapsed: false,
      items: [
        'guides/controller',
        'guides/bodyslide',
        'guides/nemesis',
        'guides/synthesis',
        'guides/lod-generation',
      ],
    },
  ],
};

export default sidebars;
